### ISSUE TITLE
Add ivy-youtube-search-history

### ISSUE THREAD

**Issue by unhammer** [squiter/ivy-youtube#6]
Could we have an ivy-youtube-specific history? Ie. change the read-string on 74 to something like

```
(let ((q (read-string 
               "Search: "
               (when ivy-youtube-search-history (car foo-hist)) 
              'ivy-youtube-search-history)))
       (push q ivy-youtube-search-history) 
       q)
```

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/squiter/ivy-youtube/6/07b94bb3-e5ad-4a2d-a73b-f99c4a23d307/c11b17d5-a460-4935-ab3b-0dd1a2940f8e) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by squiter** [comment]
Great idea @unhammer , I'm not so fluent in elisp, but I'll try to implement this.  

Do you mean a history like when you run a command with `M-:` and want to re run the command again typing `M-: M-p`?

**Comment by unhammer** [comment]
Exactly. Currently it uses a default "global" shared history, not too useful if it's been a while since last search.

**Comment by squiter** [comment]
Okay, I'll try to figure out how to do it and try to implement! Thank you for the idea :)

**Comment by squiter** [comment]
Next version will have the search history :+1:
